# zmodload zsh/zprof

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
################################################################################
[[ -s "${ZDOTDIR:-$HOME}/.zshrc_secret.zsh" ]] && . "${ZDOTDIR:-$HOME}/.zshrc_secret.zsh"
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/.ztoken" ]] && . "${ZDOTDIR:-$HOME}/.zprezto/.ztoken"
# VARIABLES
export LC_ALL=en_US.UTF-8
export PROJECT_PATH=$HOME/projects
export PATH=$HOME/bin:$HOME/.config/composer/vendor/bin:$HOME/.local/bin:$PATH
export PATH="/usr/lib/ccache/bin/:$PATH"
# export PATH="/usr/local/opt/php@7.2/sbin:/usr/local/opt/php@7.2/bin:/usr/local/opt/mariadb@10.2/bin:$PATH"
export PY_USER_BIN=$(python -c 'import site; print(site.USER_BASE + "/bin")')
export PY3_USER_BIN=$(python3 -c 'import site; print(site.USER_BASE + "/bin")')
# export PATH="$PY3_USER_BIN:$PY_USER_BIN:$PATH"
# export PATH="$HOME/.symfony/bin:$PATH"
export CGR_BIN_DIR=$HOME/.config/composer/vendor/bin
export POWERLINE_CONFIG_COMMAND="$HOME/.local/bin/powerline-config"
export EDITOR="nvim"
export VISUAL="nvim"
alias vim="nvim"
# ssh
export SSH_KEY_PATH="$HOME/.ssh/id_rsa"
# Compilation flags
export ARCHFLAGS="-arch x86_64"
# Python path
# export PYTHONPATH=/usr/local/lib/python2.7/site-packages/
# GoPath
# export GOVENDOR=$PROJECT_PATH/govendor
# export GOCODE=$PROJECT_PATH/gocode
# export GOPATH=$GOVENDOR:$GOCODE
# export PATH=$PATH:$GOVENDOR/bin:$GOCODE/bin
if (( $+commands[go] )); then
  export PATH=$PATH:$(go env GOPATH)/bin
fi
if (( $+commands[/usr/sbin/aws_completer])); then
  export PATH=/usr/sbin/:$PATH
  complete -C '/usr/sbin/aws_completer' aws
fi
if (( $+commands[ngrok] )); then
  eval "$(ngrok completion)"
fi
# export PATH="$HOME/go/bin:$PATH"
# Android
# export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_HOME=$HOME/Android/Sdk
# Git diff highlight
if [[ "$OSTYPE" == darwin* ]]; then
  export PATH=$PATH:$(brew --prefix git)/share/git-core/contrib/diff-highlight
fi
# Docker
# export DOCKER_HOST=tcp://docker.tunght.com:2376
# export DOCKER_CERT_PATH=$HOME/.docker
# export DOCKER_TLS_VERIFY=1
# export DOCKER_MACHINE_NAME="default"
# export DOCKER_MACHINE_PS1_SHOWSTATUS=true
export OVPN_DATA="ovpn-data"
# WebStorm
# export WEBSTORM_PATH=/opt/webstorm
# [[ -s $WEBSTORM_PATH ]] && export PATH=$PATH:$WEBSTORM_PATH/bin
# Facebook PathPicker
export FPP_EDITOR=subl
# Ibus
# export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
# Sound for Arch
export ALSA_CARD=HDMI
# # Hub
# export PATH="/opt/hub:$PATH"
# Gem
# export PATH="/home/rocco/.gem/ruby/2.2.0/bin:$PATH"
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
if which ruby >/dev/null && which gem >/dev/null; then
  export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
# # Heroku
# export PATH="/usr/local/heroku/bin:$PATH"
# export HISTCONTROL=ignoreboth
export BROWSER="google-chrome-stable"
export JAVA_HOME=/usr/lib/jvm/default
# fzf
if (( $+commands[rg] )); then
  if (( $+commands[git] )) then
    export FZF_DEFAULT_COMMAND='git ls-tree -r --name-only HEAD || rg --files'
  else
    export FZF_DEFAULT_COMMAND='rg --files'
  fi
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  alias grep="rg"
fi
export FZF_TMUX=1
export FZF_DEFAULT_OPTS=""
if (( $+commands[bat] )); then
  export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --preview 'bat --line-range :100 --color \"always\" {}'"
fi
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
# export PATH="$HOME/.symfony/bin:$PATH"
export CHROME_EXECUTABLE="/usr/bin/chromium"
export SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  gradle        # Gradle section
  maven         # Maven section
  node          # Node.js section
  ruby          # Ruby section
  elixir        # Elixir section
  xcode         # Xcode section
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  # gcloud        # Google Cloud Platform section
  venv          # virtualenv section
  conda         # conda virtualenv section
  # pyenv         # Pyenv section
  dotnet        # .NET section
  ember         # Ember.js section
  kubectl       # Kubectl context section
  terraform     # Terraform workspace section
  ibmcloud      # IBM Cloud section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
export SPACESHIP_GCLOUD_SHOW=false
eval "$(starship init zsh)"
# 1password-cli
# eval $(op signin my)
function 1p() {
  eval $(op signin my)
}
################################################################################
# ALIAS
alias tf="terraform"
if (( $+commands[exa] )); then
  alias ls="exa --group-directories-first"
  alias l="ls -l"
  alias la="l -a"
fi
if [[ "$OSTYPE" == darwin* ]]; then
  if (( $+commands[brew] )); then
    alias br="brew"
    alias bs="brew services"
  fi
fi
if (( $+commands[bat] )); then
  alias cat="bat --paging=never --style=plain"
fi
if (( $+commands[prettyping] )); then
  alias ping="prettyping --nolegend"
fi
if (( $+commands[ncdu] )); then
  alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
fi
# Update packages
alias updpkg="updpkgsums && makepkg --printsrcinfo | tee .SRCINFO"
# PHP
# if (( $+commands[php73] )); then
#   alias php="php73"
# fi
# Sublime
alias st="subl"
alias todo="st $HOME/my.todo"
# Laravel
alias lv="php artisan"
alias a="php artisan"
alias en="envoy run"
# robo.li
alias robo="robo.phar"
# Composer
# if (( $+commands[hhvm] )); then
#   alias composer="hhvm -v ResourceLimit.SocketDefaultTimeout=180 -v Http.SlowQueryThreshold=180000 $(which composer)"
# fi
alias mphp="php7"
# alias mphp="php"
# alias php="mphp"
# alias sphp="/usr/bin/php"
alias c="php $(which composer)"
alias c70="php70 $(which composer)"
alias c71="php71 $(which composer)"
alias c72="php72 $(which composer)"
alias c73="php73 $(which composer1)"
alias c732="php73 $(which composer)"
alias c74="php74 $(which composer)"
alias c7="php7 $(which composer)"
# Vagrant
alias v="vagrant"
# Symfony
alias sf="symfony"
alias s="mphp bin/console"
alias srs="s d:d:d --force && s d:d:cr && s d:s:c && s d:f:l --append && s h:f:l --append"
# Git
alias gfl="git flow"
if (( $+commands[hub] )); then
  eval "$(hub alias -s)"
  # [[ -s $HOME/Projects/govendor/src/github.com/`github`/hub/etc ]] && fpath=($HOME/Projects/govendor/src/github.com/github/hub/etc $fpath)
fi
# chmod
alias mx='chmod a+x'
alias 000='chmod 000'
alias 400='chmod 400'
alias 644='chmod 644'
alias 755='chmod 755'
# Random
alias makepass='openssl rand -base64 32'
# Program
alias hosts='sudo $EDITOR /etc/hosts'
alias sshconfig='$EDITOR ~/.ssh/config'
function sshm() {
  ssh $@ -t -- /bin/sh -c 'tmux has-session && exec tmux attach || exec tmux'
}
alias currentwifi="networksetup -getairportnetwork en1"
alias week='date +%V'
# IP
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias myips="ifconfig -a | perl -nle'/(\d+.\d+.\d+.\d+)/ && print $1'"
# File size
alias fs="stat -f \"%z bytes\""
if [[ "$OSTYPE" == darwin* ]]; then
  alias shuttleconfig="st $HOME/.shuttle.json"
  alias chrome='open -a "Google Chrome"'
  alias stfu="osascript -e 'set volume output muted true'"
  alias vol10="osascript -e 'set volume 10'"
  alias vol5="osascript -e 'set volume 5'"
  alias localip="ipconfig getifaddr en0"
  alias whois="whois -h whois-servers.net"
  alias flush="dscacheutil -flushcache"
  alias cleanup="find . -name '*.DS_Store' -type f -ls -delete"
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
fi
# Magento 2
# if (( $+commands[php7] )); then
#   alias mphp="php7"
# else
#   alias mphp="php"
# fi
alias mc="magento-cloud"
alias magento="mphp bin/magento"
alias mage="mphp bin/magento"
if (( $+commands[pestle.phar] )); then
  alias pestle="mphp $(which pestle.phar)"
  alias mp="pestle"
fi
alias mrf="redis-cli flushall"
alias mcg="mphp $(which mg2-codegen.phar)"
if (( $+commands[n98-magerun.phar] )); then
  alias mr="mphp $(which n98-magerun.phar)"
fi
if (( $+commands[n98-magerun2.phar] )); then
  alias mr2="mphp $(which n98-magerun2.phar)"
fi
alias m="mr2"
function deleteFolders () {
  for folder in $1; do
    if [ -d "$(pwd)/$folder" ]; then
      /usr/bin/rm -rf "$(pwd)/$folder/"
    fi
  done
}
function deleteInsideFolders () {
  for folder in $1; do
    if [[ -n "$(pwd)/$folder/"*(#qN) ]]; then
      /usr/bin/rm -rf "$(pwd)/$folder/"*
    fi
  done
}
function mcc () {
  local folders=(var/di)
  local folderGlobs=(var/generation generated/code generated/metadata var/cache var/page_cache var/session)
  deleteFolders folders
  deleteInsideFolders folderGlobs
  m c:f
}
function mcf () {
  local folderGlobs=(pub/static var/view_preprocessed)
  deleteInsideFolders folderGlobs
  m c:f
}
function mccf () {
  local folders=(var/di)
  local folderGlobs=(var/generation generated/code generated/metadata var/cache var/page_cache var/session pub/static var/view_preprocessed)
  deleteFolders folders
  deleteInsideFolders folderGlobs
  m c:f
}
alias mccfu="mccf && m setup:upgrade"
alias mcu="mrf && mcc && m setup:upgrade"
alias q="q -O -H"
alias qp="q -d '|'"
alias fp="find . -type d -exec chmod u+rwx,g+rwx,o+rx {} \; && find . -type f -exec chmod u+rw,g+rw,o+r {} \;"
function config_edit_on() {
  sudo chown -R tungha /etc/nginx /etc/php /etc/php73 /etc/php74 /etc/php7 /etc/varnish /etc/hosts /opt/openresty/nginx/
}
function config_edit_off() {
  sudo chown -R root /etc/nginx /etc/php /etc/php73 /etc/php74 /etc/php7 /etc/varnish /etc/hosts /opt/openresty/nginx/
}
function mr_base () {
  mr config:set web/unsecure/base_url "http://$1/";
  mr config:set web/secure/base_url "https://$1/";
}
function mr_base_same () {
  mr config:set web/unsecure/base_url "$1";
  mr config:set web/secure/base_url "$1";
}
function xdebug_activate() {
  if (( $+commands[$1] )); then
    if [[ -f "$2.deactivated" ]]; then
      sudo mv "$2.deactivated" "$2"
      [[ "$OSTYPE" == linux* ]] && sudo systemctl restart "$3"
      [[ "$OSTYPE" == darwin* ]] && brew services restart "$3"
    fi
  fi
}
function xdebug_deactivate() {
  if (( $+commands[$1] )); then
    if [[ -f "$2" ]]; then
      sudo mv "$2" "$2.deactivated"
      [[ "$OSTYPE" == linux* ]] && sudo systemctl restart "$3"
      [[ "$OSTYPE" == darwin* ]] && brew services restart "$3"
    fi
  fi
}
function xdebug () {
  local OSNAME=$(lsb_release -si)
  case $1 in
    on)
      if [[ "$OSTYPE" == linux* ]]; then
        if [[ "$OSNAME" == Ubuntu ]]; then
          xdebug_activate "php8.0" "/etc/php/8.0/mods-available/xdebug.ini" "php8.0-fpm.service"
          xdebug_activate "php8.1" "/etc/php/8.1/mods-available/xdebug.ini" "php8.1-fpm.service"
        else
          xdebug_activate "php70" "/etc/php70/conf.d/xdebug.ini" "php70-fpm"
          xdebug_activate "php71" "/etc/php71/conf.d/xdebug.ini" "php71-fpm"
          xdebug_activate "php72" "/etc/php72/conf.d/xdebug.ini" "php72-fpm"
          xdebug_activate "php73" "/etc/php73/conf.d/xdebug.ini" "php73-fpm"
          xdebug_activate "php74" "/etc/php74/conf.d/xdebug.ini" "php74-fpm"
          xdebug_activate "php7" "/etc/php7/conf.d/xdebug.ini" "php-fpm7"
          xdebug_activate "php80" "/etc/php80/conf.d/xdebug.ini" "php80-fpm"
          xdebug_activate "php-legacy" "/etc/php-legacy/conf.d/xdebug.ini" "php-legacy-fpm"
          xdebug_activate "php" "/etc/php/conf.d/xdebug.ini" "php-fpm"
        fi
      fi
      if [[ "$OSTYPE" == darwin* ]]; then
        xdebug_activate "php" "/usr/local/etc/php/7.2/conf.d/ext-xdebug.ini" "php@7.2"
      fi
      export XDEBUG_CONFIG="idekey=PHPSTORM"
    ;;
    off)
      if [[ "$OSTYPE" == linux* ]]; then
        if [[ "$OSNAME" == Ubuntu ]]; then
          xdebug_deactivate "php8.0" "/etc/php/8.0/mods-available/xdebug.ini" "php8.0-fpm.service"
          xdebug_deactivate "php8.1" "/etc/php/8.1/mods-available/xdebug.ini" "php8.1-fpm.service"
        else
          xdebug_deactivate "php70" "/etc/php70/conf.d/xdebug.ini" "php70-fpm"
          xdebug_deactivate "php71" "/etc/php71/conf.d/xdebug.ini" "php71-fpm"
          xdebug_deactivate "php72" "/etc/php72/conf.d/xdebug.ini" "php72-fpm"
          xdebug_deactivate "php73" "/etc/php73/conf.d/xdebug.ini" "php73-fpm"
          xdebug_deactivate "php74" "/etc/php74/conf.d/xdebug.ini" "php74-fpm"
          xdebug_deactivate "php7" "/etc/php7/conf.d/xdebug.ini" "php-fpm7"
          xdebug_deactivate "php80" "/etc/php80/conf.d/xdebug.ini" "php80-fpm"
          xdebug_deactivate "php-legacy" "/etc/php-legacy/conf.d/xdebug.ini" "php-legacy-fpm"
          xdebug_deactivate "php" "/etc/php/conf.d/xdebug.ini" "php-fpm"
        fi
      fi
      if [[ "$OSTYPE" == darwin* ]]; then
        xdebug_deactivate "php" "/usr/local/etc/php/7.2/conf.d/ext-xdebug.ini" "php@7.2"
      fi
      unset XDEBUG_CONFIG
    ;;
    *)
      echo "Usage: xdebug on|off"
    ;;
  esac
}
function phps_on() {
  local OSNAME=$(lsb_release -si)
  if (( $+commands[$1] )); then
    if [[ "$OSNAME" == Ubuntu ]]; then
      sudo update-alternatives --set php "/usr/bin/$1"
    else
      ln -sf "/usr/bin/$1" "$HOME/bin/php" && rehash
    fi
  fi
}
function phps_off() {
  local OSNAME=$(lsb_release -si)
  if [[ "$OSNAME" == Ubuntu ]]; then
    sudo update-alternatives --auto php
  else
    [ -f "$HOME/bin/php" ] && unlink "$HOME/bin/php" && rehash
  fi
}
function phps () {
  local OSNAME=$(lsb_release -si)
  case $1 in
    70)
      phps_on "php70"
    ;;
    71)
      phps_on "php71"
    ;;
    72)
      phps_on "php72"
    ;;
    80)
      if [[ "$OSNAME" == Ubuntu ]]; then
        phps_on "php8.0"
      else
        phps_on "php80"
      fi
    ;;
    81)
      if [[ "$OSNAME" == Ubuntu ]]; then
        phps_on "php8.1"
      else
        phps_on "php-legacy"
      fi
    ;;
    off)
      phps_off
    ;;
    *)
      echo "Alias php70/php71/php72/php80/php-legacy to php"
      echo "Usage: phps 70|71|72|80|81|off"
    ;;
  esac
}
# Tmux
alias tmux="tmux -2"
# npm_lazy
alias lnpm="npm --registry http://localhost:4873/"
# ag
alias ag='ag --path-to-ignore ~/.agignore'
# Anybar
function anybar { echo -n $1 | nc -4u -w0 localhost ${2:-1738}; }
# Xdebug
alias xy='export XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=127.0.0.1 remote_connect_back=0"'
alias xn='unset XDEBUG_CONFIG'
# howdoi
alias h='function hdi(){ howdoi $* -c -n 5; }; hdi'
# yii
function y {
  if [[ -s ./yiic ]] then
    ./yiic "$@"
  elif [[ -s ./protected/yiic ]]; then
    ./protected/yiic "$@"
  else
    echo "Yii not found"
    return 1
  fi
  return 0
}
alias ports="sudo lsof -iTCP -s TCP:LISTEN -P -n"
alias kc="kubectl"
alias kgc="kc -n demo"
alias hgc="hm -n demo"
################################################################################
# LIBRARY
# MeRC
[[ -s $HOME/.merc ]] && . $HOME/.merc
# # rvm
# export PATH="${HOME}/.gem/ruby/2.6.0/bin:${PATH}"
# if [[ -s $HOME/.rvm/scripts/rvm ]]; then
#   . $HOME/.rvm/scripts/rvm
#   export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
#   export PATH="${HOME}/.rvm/bin:${PATH}" # Add RVM to PATH for scripting
# fi
# Mark
# [[ -s $HOME/.mark.sh ]] && . $HOME/.mark.sh
# Perlbrew
# [[ -s $HOME/perl5/perlbrew/etc/bashrc ]] && . $HOME/perl5/perlbrew/etc/bashrc
# Wordpress
[[ -s $HOME/wp-completion.bash ]] && . $HOME/wp-completion.bash
# # NVM
# export NVM_DIR="${HOME}/.nvm"
# [ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# export NVM_DIR="$HOME/.nvm"
# [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
# [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
# source /usr/share/nvm/init-nvm.sh
# export PATH="$(yarn global bin):$PATH"

# PyEnv
# export PATH="${HOME}/.local/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PYTHON_CONFIGURE_OPTS="--enable-shared"
if (( $+commands[pyenv] )); then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

# # phpbrew
# export PHPBREW_RC_DISABLE=1
# [[ -s $HOME/.phpbrew/bashrc ]] && export PHPBREW_RC_DISABLE=1 && . $HOME/.phpbrew/bashrc
# export PHPBREW_SET_PROMPT=1

###-begin-pm2-completion-###
### credits to npm for the completion file model
#
# Installation: pm2 completion >> ~/.bashrc  (or ~/.zshrc)
#

COMP_WORDBREAKS=${COMP_WORDBREAKS/=/}
COMP_WORDBREAKS=${COMP_WORDBREAKS/@/}
export COMP_WORDBREAKS

# if type complete &>/dev/null; then
#   _pm2_completion () {
#     local si="$IFS"
#     IFS=$'\n' COMPREPLY=($(COMP_CWORD="$COMP_CWORD" \
#                            COMP_LINE="$COMP_LINE" \
#                            COMP_POINT="$COMP_POINT" \
#                            pm2 completion -- "${COMP_WORDS[@]}" \
#                            2>/dev/null)) || return $?
#     IFS="$si"
#   }
#   complete -o default -F _pm2_completion pm2
# elif type compctl &>/dev/null; then
#   _pm2_completion () {
#     local cword line point words si
#     read -Ac words
#     read -cn cword
#     let cword-=1
#     read -l line
#     read -ln point
#     si="$IFS"
#     IFS=$'\n' reply=($(COMP_CWORD="$cword" \
#                        COMP_LINE="$line" \
#                        COMP_POINT="$point" \
#                        pm2 completion -- "${words[@]}" \
#                        2>/dev/null)) || return $?
#     IFS="$si"
#   }
#   compctl -K _pm2_completion + -f + pm2
# fi
# ###-end-pm2-completion-###

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

transfer() {
  if [ $# -eq 0 ]; then
    echo "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md";
    return 1;
  fi
  tmpfile=$( mktemp -t transferXXX );
  if tty -s; then
    basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g');
    curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile;
  else
    curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile;
  fi;
  echo "" >> $tmpfile;
  cat $tmpfile;
  rm -f $tmpfile;
}

test -e "$HOME/k/k.sh" && source "$HOME/k/k.sh"
alias ka="k -Ah --no-vcs"

if [[ "$OSTYPE" == darwin* ]]; then
  test -e "$(brew --prefix asdf)/asdf.sh" && source "$(brew --prefix asdf)/asdf.sh"
  test -e "$(brew --prefix asdf)/asdf.sh" && asdf reshim python
  test -e "$(brew --prefix asdf)/completions/asdf.bash" && source "$(brew --prefix asdf)/completions/asdf.bash"
fi
test -e "$PROJECT_PATH/github/fcambus/ansiweather/ansiweather.plugin.zsh" && source "$PROJECT_PATH/github/fcambus/ansiweather/ansiweather.plugin.zsh"
# test -e "$(brew --prefix asdf)/asdf.sh" && source "$(brew --prefix asdf)/asdf.sh"
# test -e "$(brew --prefix asdf)/asdf.sh" && asdf reshim python
# test -e "$(brew --prefix asdf)/completions/asdf.bash" && source "$(brew --prefix asdf)/completions/asdf.bash"

# # zsh-nvm
# [[ -s "${HOME}/.zsh-nvm/zsh-nvm.plugin.zsh" ]] && . "${HOME}/.zsh-nvm/zsh-nvm.plugin.zsh"
# [[ -s "${HOME}/.zsh-better-npm-completion/zsh-better-npm-completion.plugin.zsh" ]] && . "${HOME}/.zsh-better-npm-completion/zsh-better-npm-completion.plugin.zsh"
# luarocks
if (( $+commands[luarocks] )); then
  # eval $(luarocks path --bin)
  export PATH=$PATH:$HOME/.luarocks/bin
fi

# FZF
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
# deployer
# [[ -s $HOME/.deployer_completion ]] && source $HOME/.deployer_completion
# Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi
# ulimit -S -n 20480
ulimit -S -n 4096
# if which ruby >/dev/null && which gem >/dev/null; then
#   PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
# fi
# BEGIN SNIPPET: Magento Cloud CLI configuration
# export PATH="$HOME/"'.magento-cloud/bin':"$PATH"
# if [ -f "$HOME/"'.magento-cloud/shell-config.rc' ]; then . "$HOME/"'.magento-cloud/shell-config.rc'; fi
# END SNIPPET
alias sm="synthmanager"

# added by travis gem
[ -f /Users/tunghathe/.travis/travis.sh ] && source /Users/tunghathe/.travis/travis.sh
# tmuxinator
[ -f /usr/local/share/zsh/site-functions/_tmuxinator ] && source /usr/local/share/zsh/site-functions/_tmuxinator
alias mux="tmuxinator"

# zprof
# source /usr/share/nvm/init-nvm.sh

# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#   exec tmux
# fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# fnm
# export PATH=/home/tungha/.fnm:$PATH
# eval "`fnm env`"
alias ggg="googler"
alias hm="helm"
alias kc="kubectl"
alias hmh="hm --namespace headless"
alias kch="kc -n headless"
alias kcha="kc -n headless-api"
alias kci="kc -n inventory"
alias hmo="hm --namespace oms"
alias kco="kc -n oms"
alias hm24="hm --namespace magento24"
alias kc24="kc -n magento24"
alias kco="kc -n oms"
alias kcp="kc -n product-feed"
alias kcw="kc -n wh3pl"

# alias gcloud="docker run --rm -v "${HOME}/.config/gcloud":/root/.config/gcloud -v "${HOME}/.kube":/root/.kube gcr.io/google.com/cloudsdktool/google-cloud-cli:latest gcloud"
# alias gc="gcloud"
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

alias bashly='docker run --rm -it --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly'

function warm_urls() {
  echo ' Connect  | Transfer |  Total   | Status  | URL'
  echo '----------|----------|----------|---------|----'
  cat "$1" | while read line; do
    curl -so /dev/null -w " %{time_connect} | %{time_starttransfer} | %{time_total} |   %{http_code}   " $line
    echo "| $line"
  done
}
# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
# export VOLTA_HOME="$HOME/.volta"
# export PATH="$VOLTA_HOME/bin:$PATH"

# twilio autocomplete setup
TWILIO_AC_ZSH_SETUP_PATH=/home/tungha/.twilio-cli/autocomplete/zsh_setup && test -f $TWILIO_AC_ZSH_SETUP_PATH && source $TWILIO_AC_ZSH_SETUP_PATH;

SSLKEYLOGFILE=~/.ssl-key.log

xmodmap ~/.xmodmaprc
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
